name: Backend-CI

on:
  push:
    branches:
      - test-cicd-vitest

permissions:
  contents: read
  packages: write

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./chat-server

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: ./chat-server/package-lock.json

      - run: npm ci

  cd:
    needs: backend-ci
    uses: ./.github/workflows/backend-cd.yml