name: Frontend-CI

on:
  push:
    branches:
      - test-cicd-docker

permissions:
  contents: read
  packages: write

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./chat-client

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./chat-client/package-lock.json

      - run: npm ci

      - run: npm test
      
      - run: npm run build

  frontend-cd:
    needs: frontend-ci
    uses: ./.github/workflows/frontend-cd.yml