name: Socket-CI

on:
  push:
    branches:
      - test-cicd-vitest

permissions:
  contents: read
  packages: write

jobs:
  socket-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./socket

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: ./socket/package-lock.json

      - run: npm ci

  cd:
    needs: socket-ci
    uses: ./.github/workflows/socket-cd.yml